// This file is automatically generated. Do not modify.
export const firebaseConfig = {
  apiKey: "AIzaSyB3PfVMrF-aAnNu1sV4n-cgGdZ0cap-phg",
  authDomain: "crested-acumen-478807-t9.firebaseapp.com",
  databaseURL: "https://crested-acumen-478807-t9-default-rtdb.asia-southeast1.firebasedatabase.app",
  projectId: "crested-acumen-478807-t9",
  storageBucket: "crested-acumen-478807-t9.firebasestorage.app",
  messagingSenderId: "455832172522",
  appId: "1:455832172522:web:5f0a443b0320ac56412493"
};
