// This file is automatically generated. Do not modify.
export const firebaseConfig = {
  apiKey: "AIzaSyCDWQtZpgb_n4aDOHCjWWd6jqe6V3ZD_PE",
  authDomain: "lemburku-32c97.firebaseapp.com",
  projectId: "lemburku-32c97",
  storageBucket: "lemburku-32c97.firebasestorage.app",
  messagingSenderId: "1014652947916",
  appId: "1:1014652947916:web:9889c5a9adbcacad78a169",
  measurementId: "G-GGNL8NBXX9"
};
