// This file is automatically generated. Do not modify.
export const firebaseConfig = {
  apiKey: "AIzaSyA6p1zDRn-Kx7IGFT4dszAl74z255DBwc4",
  authDomain: "studio-4644022499-ad076.firebaseapp.com",
  projectId: "studio-4644022499-ad076",
  storageBucket: "studio-4644022499-ad076.firebasestorage.app",
  messagingSenderId: "927061177360",
  appId: "1:927061177360:web:4d13412a62880002b58695"
};
